### PR TITLE
Milestone 1

### PR DESCRIPTION
**Pull request by pbkabali**
## What this PR does
- Creates a new react application
- Adds other project dependencies
- Adds styles and ES linters
- Adds a [live link](https://shielded-everglades-20664.herokuapp.com/) for the app deployed on the Heroku platform

### CODE REVIEW

**Review by trekab — CHANGES_REQUESTED** [review]
### Changes Required! :recycle: 
Well done @pbkabali! There is just one required step for you to make in order to finish this milestone. i.e:
- [x] Delete unnecessary files or assets, such as the React svg Logo.([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/react_reducx/calculator/milestone1/files-removed.png) from [pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/44896085/))

__Kindly make the necessary changes and submit another code review request.__
_Feel free to reach me on slack for any inquiries about this review._ :wink: 
__Treasure Kabareebe__
[Portfolio](https://trekab.github.io/portfolio/) | [LinkedIn](https://www.linkedin.com/in/treasure-kabareebe/) | [Twitter](https://twitter.com/TKabareebe)

**Comment by pbkabali** [comment]
I appreciate your review @trekab. Thanks a lot. I have removed the files and requested for another review.

**Review by SpaYco — APPROVED** [review]
# Project Approved ✔️ 

thank you for making the required changes, your project is now approved!

### please don't forget to merge to master, good luck with the next projects!


Best, 
Aziz Mejri 
_contact me on [twitter](https://twitter.com/iSpaYco) or slack (@SpaYco) if you need any help_

**Comment by pbkabali** [comment]
Dear @Spayco, thank you so much for your time and effort.

**Pull request merged**
